#
# Labtainer Dockerfile
#
#  This is the default Labtainer Dockerfile template, plesae choose the appropriate
#  base image below.
#
# The labtainer.base image includes the following packages:
#    build-essential  expect  file  gcc-multilib  gdb  iputils-ping  less  man  manpages-dev 
#    net-tools  openssh-client  python  sudo  tcl8.6  vim  zip  hexedit  rsyslog
#
# The labtainer.network image adds the following packages:
#   openssl openssh-server openvpn wget tcpdump  update-inetd  xinetd
#
ARG registry
FROM $registry/labtainer.base2
#FROM $registry/labtainer.network
#FROM $registry/labtainer.centos
#FROM $registry/labtainer.lamp
#
#  lab is the fully qualified image name, e.g., mylab.some_container.student
#  labdir is the name of the lab, e.g., mylab 
#  imagedir is the name of the container
#  user_name is the USER from the start.config, if other than ubuntu,
#            then that user must be added in this dockerfile
#            before the USER command
#
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
#
#  put package installation here, e.g.,
#     RUN apt-get update && apt-get install -y --no-install-recommends somepackage
#
#
#
# Install the system files found in the _system directory
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /
#
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo
# replace above with below for centos/fedora
#RUN usermod $user_name -a -G wheel


#
#  **** Perform all root operations, e.g.,           ****
#  **** "apt-get install" prior to the USER command. ****
#
USER $user_name
ENV HOME /home/$user_name
#
# Install files in the user home directory
#
#ADD $labdir/$imagedir/home_tar/home.tar $HOME
# remove after docker fixes problem with empty tars
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME
#
#  The first thing that executes on the container.
#
USER root
RUN apt install -y kmod && apt clean
RUN apt-get update && apt-get install -y wget
RUN dpkg -i /home/ubuntu/linux-headers-4.18.0-15_4.18.0-15.16~18.04.1_all.deb || apt-get install -f -y
RUN wget -O /tmp/linux-headers-4.18.0-15-generic_4.18.0-15.16~18.04.1_amd64.deb https://security.ubuntu.com/ubuntu/pool/main/l/linux-hwe/linux-headers-4.18.0-15-generic_4.18.0-15.16~18.04.1_amd64.deb
RUN dpkg -i /tmp/linux-headers-4.18.0-15-generic_4.18.0-15.16~18.04.1_amd64.deb || apt-get install -f -y
RUN rm /tmp/linux-headers-4.18.0-15-generic_4.18.0-15.16~18.04.1_amd64.deb
RUN apt-get -y install libelf-dev
RUN apt install -y build-essential libncurses-dev linux-headers-$(uname -r)
RUN rm /home/ubuntu/linux-headers-4.18.0-15_4.18.0-15.16~18.04.1_all.deb
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

